config/routes.rb
Rails.application.routes.draw do

  get 'foo/bar'
  get 'foo/baz'

  get     '/help',    to: 'static_pages#help'
  get     '/about',   to: 'static_pages#about'
  get     '/contact', to: 'static_pages#contact'
  get     '/home',    to: 'static_pages#home'
  get     '/signup',  to: 'users#new'
  post    '/signup',  to: 'users#create'
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  'logout',   to: 'sessions#destroy'
  get 'follow-request', to: 'relationships#index'


  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :microposts
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :microposts do
    member do
      put 'like', to: 'votes#like'
      put 'dislike', to: 'votes#dislike'
      put 'favorite', to: 'votes#favorite'
    end
  end

  resources :relationships do
    member do
      put 'accept', to: 'relationships#accept_status'
      put 'denied', to: 'relationships#denied_status'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true

  enum status: [:accepted, :denied, :waiting_for_acceptance]
  default_scope -> { where(status: :accepted)}

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :logged_in_user
  before_action :user_has_private_profile, only: [:index, :accept_status, :denied_status]

  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
    @microposts = @user.micropost_by_user(current_user).paginate(page: params[:page])
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow(@user)
    @microposts = @user.micropost_by_user(current_user).paginate(page: params[:page])
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def index
    @relationships = Relationship
                         .unscoped
                         .order(created_at: :desc, status: :desc)
                         .where("follower_id = ?", current_user.id)
                         .paginate(page: params[:page])
  end

  def accept_status
    @relationship = Relationship.unscoped.find(params[:id])
    @relationship.accepted!
    redirect :accepted
  end

  def denied_status
    @relationship = Relationship.unscoped.find(params[:id])
    @relationship.denied!
    redirect :denied
  end

  private
    def user_has_private_profile
      redirect_to(root_url) unless current_user.private_profile?
    end

    def redirect(type)
      flash[:success] = "Successful #{type} status"
      redirect_to follow_request_url
    end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_relationship.html.erb
<li>
  <%= gravatar_for relationship.followed, size: 50 %>
  <span class="user">
    <%= link_to relationship.followed.name, user_path(relationship.followed) %>
  </span>
  <span class="status">
    <%= relationship.status.humanize %>
  </span>
  <span class="actions">
      <span>
        <%= link_to 'accept', accept_relationship_path(relationship), method: :put %>
      </span>
      <span>
        <%= link_to 'denied', denied_relationship_path(relationship), method: :put %>
      </span>
  </span>

</li>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");
$("#followers").html('<%= @user.followers.count %>');
$("#microposts").html("<%= escape_javascript(render('users/microposts')) %>");

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");
$("#followers").html('<%= @user.followers.count %>');
$("#microposts").html("<%= escape_javascript(render('users/microposts')) %>");

app/views/relationships/index.html.erb
<% provide(:title, 'All follow request') %>
<h1>All follow request</h1>

<%= will_paginate %>

<ol class="relationship">
  <%= render @relationships %>
</ol>

<%= will_paginate %>